### PR TITLE
Net Code rework

### PR DESCRIPTION
**Pull request by Minepolz320**
backpacks have different colors and models

### CODE REVIEW

**Comment by Minepolz320** [comment]
Soo any suggestions here?

**Comment by eigenraven** [comment]
It's a pretty big change to code, let's wait until stable is finished with this

**Comment by Dream-Master** [comment]
@Minepolz320 @eigenraven stable is out

**Comment by Minepolz320** [comment]
So?

**Comment by RinWate** [comment]
Any updates?

**Comment by Dream-Master** [comment]
I will add a pre tag in a min so people can test the version

**Comment by Minepolz320** [comment]
@Dream-Master Thanks you, it's just that I can forget what I did and it will be more difficult for me to fix problems if they appear later

**Comment by Dream-Master** [comment]
for testing * https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/releases/tag/2.2.7-GTNH-pre

**Comment by Dream-Master** [comment]
is in 2.2.7 anyways lets merge this

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
